# Generated by Django 5.1.2 on 2025-12-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0002_remove_foro_categoria_alter_foro_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foro',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
