# Generated by Django 5.1.2 on 2025-11-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('psicologo', 'Psicologo'), ('paciente', 'Paciente'), ('admin', 'Admin')], default='Paciente', max_length=30),
            preserve_default=False,
        ),
    ]
