<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-11-26 14:42
=======
# Generated by Django 5.1.1 on 2025-11-26 14:49
>>>>>>> 96a3dac10d097119f944b0f215b8da73059c6124

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_rol_paciente_psicologo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='psicologo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psicologo_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
