# Generated by Django 5.1.2 on 2025-12-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_paciente_usuario_alter_psicologo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='img_perfil',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
