# Generated by Django 5.1.2 on 2025-11-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=30)),
                ('ubicacion', models.TextField()),
            ],
        ),
    ]
